/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ayasi
 */
package stajprojesi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class girisKayitFrame extends javax.swing.JFrame {

    /**
     * Creates new form girisKayitFrame
     */
    public girisKayitFrame() {
        initComponents();
        radioBtnHidden.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFieldCekiciPlaka = new javax.swing.JTextField();
        txtFieldDorsePlaka = new javax.swing.JTextField();
        radioBtnGiris = new javax.swing.JRadioButton();
        radioBtnCikis = new javax.swing.JRadioButton();
        btnGirisKaydet = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFieldGirisTarih = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFieldGirisSaat = new javax.swing.JTextField();
        btnGirisExit = new javax.swing.JButton();
        radioBtnHidden = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Çekici Plaka:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Dorse Plaka:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Yön Bilgisi:");

        txtFieldCekiciPlaka.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFieldCekiciPlaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCekiciPlakaActionPerformed(evt);
            }
        });

        txtFieldDorsePlaka.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFieldDorsePlaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDorsePlakaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnGiris);
        radioBtnGiris.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioBtnGiris.setText("Türkiye'ye Giriş");
        radioBtnGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radioBtnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnGirisActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnCikis);
        radioBtnCikis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioBtnCikis.setText("Türkiye'den Çıkış");
        radioBtnCikis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGirisKaydet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGirisKaydet.setText("Kaydet");
        btnGirisKaydet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGirisKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisKaydetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Giriş Kayıt");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Tarih:");

        txtFieldGirisTarih.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Saat:");

        txtFieldGirisSaat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnGirisExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGirisExit.setText("Ana Sayfaya Dön");
        btnGirisExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGirisExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisExitActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnHidden);
        radioBtnHidden.setText("jRadioButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldCekiciPlaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(45, 45, 45)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldDorsePlaka)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(radioBtnGiris)
                                .addGap(48, 48, 48)
                                .addComponent(radioBtnCikis)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldGirisTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldGirisSaat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioBtnHidden))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGirisKaydet)
                        .addGap(68, 68, 68)
                        .addComponent(btnGirisExit)
                        .addGap(165, 165, 165)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(334, 335, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldCekiciPlaka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldDorsePlaka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioBtnGiris)
                    .addComponent(radioBtnCikis))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtFieldGirisTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtFieldGirisSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(radioBtnHidden)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGirisKaydet)
                    .addComponent(btnGirisExit))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldCekiciPlakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCekiciPlakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCekiciPlakaActionPerformed

    private void txtFieldDorsePlakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDorsePlakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDorsePlakaActionPerformed

    private void radioBtnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnGirisActionPerformed
        
    }//GEN-LAST:event_radioBtnGirisActionPerformed

    private void btnGirisExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisExitActionPerformed
        mainFrame main = new mainFrame();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGirisExitActionPerformed

    private void btnGirisKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisKaydetActionPerformed
        Connection connection=null;
        DbHelper dbHelper=new DbHelper();
        PreparedStatement statement =null;
        
        String yön = "";
        if(radioBtnGiris.isSelected()){
            yön="Türkiye'ye Geliş";
        }else if(radioBtnCikis.isSelected()){
            yön="Türkiye'den Çıkış";
        }
        
        try{
            connection = dbHelper.getConnection();
            String sql = "insert into girisKayit (cekiciPlaka,dorsePlaka,yonBilgisi,girisTarihi,girisSaati) values(?,?,?,?,?)";
            statement = connection.prepareStatement(sql);
            statement.setString(1,txtFieldCekiciPlaka.getText());
            statement.setString(2,txtFieldDorsePlaka.getText());
            statement.setString(3,yön);
            statement.setString(4,txtFieldGirisTarih.getText());
            statement.setString(5,txtFieldGirisSaat.getText());
            int result = statement.executeUpdate();
        }catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
        }finally{
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
                
            }
        }
        
        txtFieldCekiciPlaka.setText("");
        txtFieldDorsePlaka.setText("");
        txtFieldGirisTarih.setText("");
        txtFieldGirisSaat.setText("");
        radioBtnHidden.setSelected(true);
        
    }//GEN-LAST:event_btnGirisKaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisKayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisKayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisKayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisKayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisKayitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGirisExit;
    private javax.swing.JButton btnGirisKaydet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton radioBtnCikis;
    private javax.swing.JRadioButton radioBtnGiris;
    private javax.swing.JRadioButton radioBtnHidden;
    private javax.swing.JTextField txtFieldCekiciPlaka;
    private javax.swing.JTextField txtFieldDorsePlaka;
    private javax.swing.JTextField txtFieldGirisSaat;
    private javax.swing.JTextField txtFieldGirisTarih;
    // End of variables declaration//GEN-END:variables
}
