/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ayasi
 */

package stajprojesi;

public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGirisKayit = new javax.swing.JButton();
        btnTescilKayit = new javax.swing.JButton();
        btnCikisKayit = new javax.swing.JButton();
        btnSorgula = new javax.swing.JButton();
        btnXray = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGirisKayit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGirisKayit.setText("Giriş Kayıt");
        btnGirisKayit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGirisKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisKayitActionPerformed(evt);
            }
        });

        btnTescilKayit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTescilKayit.setText("Tescil Kayıt");
        btnTescilKayit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTescilKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTescilKayitActionPerformed(evt);
            }
        });

        btnCikisKayit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCikisKayit.setText("Çıkış Kayıt");
        btnCikisKayit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCikisKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisKayitActionPerformed(evt);
            }
        });

        btnSorgula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSorgula.setText("Sorgula");
        btnSorgula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorgulaActionPerformed(evt);
            }
        });

        btnXray.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnXray.setText("X-Ray Sevk");
        btnXray.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXrayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGirisKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnTescilKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXray, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btnCikisKayit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnTescilKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCikisKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGirisKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXray, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisKayitActionPerformed
        girisKayitFrame girisKayit = new girisKayitFrame();
        girisKayit.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGirisKayitActionPerformed

    private void btnXrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXrayActionPerformed
        xraySevkFrame xraySevk = new xraySevkFrame();
        xraySevk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnXrayActionPerformed

    private void btnTescilKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTescilKayitActionPerformed
        tescilKayitFrame tescilKayit = new tescilKayitFrame();
        tescilKayit.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTescilKayitActionPerformed

    private void btnCikisKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisKayitActionPerformed
        cikisKayitFrame cikisKayit = new cikisKayitFrame();
        cikisKayit.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCikisKayitActionPerformed

    private void btnSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorgulaActionPerformed
        sorguFrame sorgu = new sorguFrame();
        sorgu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSorgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikisKayit;
    private javax.swing.JButton btnGirisKayit;
    private javax.swing.JButton btnSorgula;
    private javax.swing.JButton btnTescilKayit;
    private javax.swing.JButton btnXray;
    // End of variables declaration//GEN-END:variables
}
